# Generated by Django 2.1.4 on 2020-08-23 03:10

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Drug',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, validators=[api.models.validate_rut])),
                ('dose', models.DecimalField(decimal_places=2, max_digits=3, validators=[api.models.validate_dose])),
                ('date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Drug')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'ordering': ['id'],
            },
        ),
    ]
